import {defineType, defineField} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  description: 'Global site-wide settings used across every page',
  groups: [
    {name: 'branding', title: 'Branding'},
    {name: 'contact', title: 'Contact'},
    {name: 'social', title: 'Social'},
    {name: 'seo', title: 'Default SEO'},
  ],
  fields: [
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      description: 'The name of the business (e.g. "CEO Hosting U")',
      group: 'branding',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'logo',
      title: 'Primary Logo',
      type: 'image',
      description: 'Main logo shown in the header',
      group: 'branding',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alt Text', type: 'string'})],
    }),
    defineField({
      name: 'triadBadge',
      title: 'Triad Badge',
      type: 'image',
      description: 'Badge image used in the Triad Authority section',
      group: 'branding',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alt Text', type: 'string'})],
    }),
    defineField({
      name: 'smartSystemsBadge',
      title: 'Smart Systems Badge',
      type: 'image',
      description: 'Badge image for the Smart Systems section',
      group: 'branding',
      options: {hotspot: true},
      fields: [defineField({name: 'alt', title: 'Alt Text', type: 'string'})],
    }),
    defineField({
      name: 'ogImage',
      title: 'Default Social Share Image',
      type: 'image',
      description: 'Used when a page is shared on social media and no page-specific image is set. Recommended: 1200×630.',
      group: 'branding',
      options: {hotspot: true},
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      group: 'contact',
      validation: (Rule) => Rule.email(),
    }),
    defineField({
      name: 'contactPhone',
      title: 'Contact Phone (tel format)',
      type: 'string',
      description: 'Raw phone number used in tel: links, e.g. "+13368835635"',
      group: 'contact',
    }),
    defineField({
      name: 'phoneDisplay',
      title: 'Phone Display',
      type: 'string',
      description: 'How the phone number is displayed, e.g. "(336) 883-5635"',
      group: 'contact',
    }),
    defineField({
      name: 'location',
      title: 'Location',
      type: 'string',
      description: 'Primary location, e.g. "Lexington, NC"',
      group: 'contact',
    }),
    defineField({
      name: 'locationDescription',
      title: 'Location Description',
      type: 'string',
      description: 'Secondary location label, e.g. "Serving the Triad"',
      group: 'contact',
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'array',
      of: [{type: 'socialLink'}],
      group: 'social',
    }),
    defineField({
      name: 'defaultSeo',
      title: 'Default SEO',
      type: 'seo',
      description: 'Fallback SEO values used when a page doesn\'t set its own',
      group: 'seo',
    }),
  ],
  preview: {
    select: {title: 'siteName', media: 'logo'},
    prepare({title, media}) {
      return {title: title || 'Site Settings', media}
    },
  },
})
